export const StatusCode = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
};
export const ReasonStatusCode = {
  [StatusCode.CONTINUE]: 'Continue',
  [StatusCode.SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [StatusCode.PROCESSING]: 'Processing',
  [StatusCode.EARLY_HINTS]: 'Early Hints',
  [StatusCode.OK]: 'OK',
  [StatusCode.CREATED]: 'Created',
  [StatusCode.ACCEPTED]: 'Accepted',
  [StatusCode.NON_AUTHORITATIVE_INFORMATION]: 'Non-Authoritative Information',
  [StatusCode.NO_CONTENT]: 'No Content',
  [StatusCode.RESET_CONTENT]: 'Reset Content',
  [StatusCode.PARTIAL_CONTENT]: 'Partial Content',
  [StatusCode.MULTI_STATUS]: 'Multi-Status',
  [StatusCode.ALREADY_REPORTED]: 'Already Reported',
  [StatusCode.IM_USED]: 'IM Used',
  [StatusCode.MULTIPLE_CHOICES]: 'Multiple Choices',
  [StatusCode.MOVED_PERMANENTLY]: 'Moved Permanently',
  [StatusCode.FOUND]: 'Found',
  [StatusCode.SEE_OTHER]: 'See Other',
  [StatusCode.NOT_MODIFIED]: 'Not Modified',
  [StatusCode.USE_PROXY]: 'Use Proxy',
  [StatusCode.TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [StatusCode.PERMANENT_REDIRECT]: 'Permanent Redirect',
  [StatusCode.BAD_REQUEST]: 'Bad Request',
  [StatusCode.UNAUTHORIZED]: 'Unauthorized',
  [StatusCode.PAYMENT_REQUIRED]: 'Payment Required',
  [StatusCode.FORBIDDEN]: 'Forbidden',
  [StatusCode.NOT_FOUND]: 'Not Found',
  [StatusCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [StatusCode.NOT_ACCEPTABLE]: 'Not Acceptable',
  [StatusCode.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [StatusCode.REQUEST_TIMEOUT]: 'Request Timeout',
  [StatusCode.CONFLICT]: 'Conflict',
  [StatusCode.GONE]: 'Gone',
  [StatusCode.LENGTH_REQUIRED]: 'Length Required',
  [StatusCode.PRECONDITION_FAILED]: 'Precondition Failed',
  [StatusCode.PAYLOAD_TOO_LARGE]: 'Payload Too Large',
  [StatusCode.URI_TOO_LONG]: 'URI Too Long',
  [StatusCode.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [StatusCode.RANGE_NOT_SATISFIABLE]: 'Range Not Satisfiable',
  [StatusCode.EXPECTATION_FAILED]: 'Expectation Failed',
  [StatusCode.IM_A_TEAPOT]: "I'm a teapot",
  [StatusCode.MISDIRECTED_REQUEST]: 'Misdirected Request',
  [StatusCode.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [StatusCode.LOCKED]: 'Locked',
  [StatusCode.FAILED_DEPENDENCY]: 'Failed Dependency',
  [StatusCode.TOO_EARLY]: 'Too Early',
  [StatusCode.UPGRADE_REQUIRED]: 'Upgrade Required',
  [StatusCode.PRECONDITION_REQUIRED]: 'Precondition Required',
  [StatusCode.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [StatusCode.REQUEST_HEADER_FIELDS_TOO_LARGE]:
    'Request Header Fields Too Large',
  [StatusCode.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable For Legal Reasons',
  [StatusCode.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [StatusCode.NOT_IMPLEMENTED]: 'Not Implemented',
  [StatusCode.BAD_GATEWAY]: 'Bad Gateway',
  [StatusCode.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [StatusCode.GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [StatusCode.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [StatusCode.VARIANT_ALSO_NEGOTIATES]: 'Variant Also Negotiates',
  [StatusCode.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [StatusCode.LOOP_DETECTED]: 'Loop Detected',
  [StatusCode.NOT_EXTENDED]: 'Not Extended',
  [StatusCode.NETWORK_AUTHENTICATION_REQUIRED]:
    'Network Authentication Required',
};
